name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # updates daily
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: AdharvM24
          template: classic
          base: header, activity, community, repositories

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage

          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_commit: yes
          plugin_commit_timezone: Asia/Kolkata

          plugin_followup: yes
          plugin_lines: yes
